apiVersion: ocm.software/v3alpha1
kind: ComponentVersion
metadata:
  name: github.com/sidhishruti22/frontend
  provider:
    name: sidhishruti22
  version: v1.0.1
repositoryContexts: []
spec:
  resources:
  - access:
      localReference: sha256.c23a1477a5aad650be9223e8c30e2a02dc67bb32f2690705f3f8d292f187288e
      mediaType: application/yaml
      type: localBlob
    name: config
    relation: local
    type: configdata.ocm.software
    version: v1.0.1
  - access:
      imageReference: ammar31/python-django-2.3
      type: ociArtifact
    name: image
    relation: external
    type: ociImage
    version: 6.2.0
  - access:
      localReference: sha256.953a359c285472afd54f1ef5c9bc69bb89aac62250c552e652839e6f2d238e79
      mediaType: application/x-tgz
      type: localBlob
    name: manifests
    relation: local
    type: kustomize.ocm.fluxcd.io
    version: v1.0.1
