apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: ocm-app-podify
  namespace: ocm-system
spec:
  interval: 10m0s
  component: ghcr.io/sidhishruti22/ocm-app-podify
  version:
    semver: v1.0.1-dev
  repository:
    url: ghcr.io/sidhishruti22/ocm-app-ex-podify
    secretRef:
      name: creds
  references:
    expand: true
