apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: ocm-app-podify-deployment
  namespace: ocm-system
spec:
  interval: 10m0s
  componentVersionRef:
    name: ocm-app-podify
    namespace: ocm-system
  resource:
    name: deployment
  snapshotTemplate:
    name: podinfo-deployment
